# .hadolint.yaml
ignored:
  - DL3018 # Esta regla se aplica a 'apk add'
override:
  DL3018: # Configuración específica para DL3018
    packages: # Lista de paquetes para los cuales ignorar DL3018
      - ca-certificates