---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service
  namespace: reservation-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-service
  template:
    metadata:
      labels:
        app: resource-service
    spec:
      containers:
        - name: resource-service
          image: resource-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
          envFrom:
            - configMapRef:
                name: app-config
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      livenessProbe:
        httpGet:
          path: /health
          port: 8082
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /health
          port: 8082
        initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: reservation-system
spec:
  selector:
    app: resource-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
